### ISSUE TITLE
Add new error case BuildGraphError::AddingEdgeError

### ISSUE THREAD

**Issue by pdodev** [gcfbn/learning_rust#24]
1. Nowy enum AddingEdgeError
   - TooManyEdges (przenieść z BuildGraphError)
   - WrongFromIndex (przenieść z EdgeDescriptionError)
   - WrongToIndex  (przenieść z EdgeDescriptionError)
2. Nowy error case:
    BuildGraphError::AddingEdgeError(AddingEdgeError)

**Comment by gcfbn** [comment]
Wtedy można rozważyć połączenie enum EdgeDescriptionError i (poprawionego) CreatingEdgeError w jedno (powiedzmy EdgeParsingError), które podobnie jak GraphParametersParsingError będzie dotyczyć brakujących danych lub danych złego typu
