### ISSUE TITLE
Branch documentation

### ISSUE THREAD

**Issue by pdodev** [gcfbn/learning_rust#40]
... wydaje mi się, że powinien wychodzić od main-a już **po** zmergowaniu pdo_rename_dirs.
Czy na pewno tak chciałeś jak jest teraz ?

Po wykonaniu komendy:
```
git checkout documentation
```

znika katalog `graphs`, a pojawia się `kruskals_algorithm`.

**Comment by gcfbn** [comment]
Nie chciałem, byłem pewny, że zrobiłem `git pull`, spróbuję te zmiany teraz jakoś połączyć

**Comment by gcfbn** [comment]
Naprawione w 5f44d17feb92736abb9ddd171d52dd4092a771d9
