### ISSUE TITLE
Rename: GraphFileReader -> GraphDescriptionReader

### ISSUE THREAD

**Issue by pdodev** [gcfbn/learning_rust#44]
Po ostatnich poprawkach na branchu: `documentation` i pojawieniu się funkcji `build_graph_from_string`
proponuję zmienić nzwę `GraphFileReader` na `GraphDescriptionReader`.

Ale to dopiero po zmergowaniu tego branch-a do main-a.

**Comment by gcfbn** [comment]
Fixed in commit 866fa43
