### ISSUE TITLE
Dodawanie generowania pliku z grafem do Clap-a - jak zrobić to lepiej?

### ISSUE THREAD

**Issue by gcfbn** [gcfbn/learning_rust#45]
Wydaje mi się, że najlepiej będzie to wyglądać przy użyciu subkomend:
`runner task <plik_wejsciowy>` <- to co jest teraz można przerobić na subkomendę
`runner graph-file-generator <plik_wyjsciowy> <liczba_wezlow> <liczba_krawedzi> <max_waga>` <- nowa subkomenda

Mam coś takiego:

``` rust
use clap::{AppSettings, Clap};
use graph::Result;
use std::path::{PathBuf};
use std::process;

#[derive(Debug, Clap)]
#[clap(
// nazwa, autor, itd...
setting = AppSettings::ArgRequiredElseHelp,
)]
struct CmdArgs {
    #[clap(subcommand)]
    pub subcommand: SubCommand,
}

#[derive(Clap, Debug)]
enum SubCommand {
    #[clap()]
    GraphFileGenerator(GraphFileGeneratorParameters),
    #[clap()]
    Task(TaskData),
}

#[derive(Clap, Debug)]
struct GraphFileGeneratorParameters {
    output: PathBuf,
    nodes_count: u32,
    edges_count: u32,
    max_weight: u32,
}

#[derive(Clap, Debug)]
struct TaskData {
    task_file: PathBuf,
}
```

Wtedy funkcja run() wygląda tak:
``` rust
let cmd_args: CmdArgs = CmdArgs::parse();

match cmd_args.subcommand {
        SubCommand::Task(task_data) => {
            let graph = graph::build_graph_from_file(task_data.task_file)?;
            let output = algorithms::calculate_min_total_weight(graph);
            println!("{}", output);
        }

        SubCommand::GraphFileGenerator(params) => generate_graph(params), // na razie nie implementowałem tej funkcji
    }
    Ok(())
}
```

Zniknęła walidacja - czy plik istnieje, bo `validator` nie może być dodany do subkomendy, jedynie do pola struct-a.
Poza tym, wrapowanie PathBuf do TaskData (który jest structem z jednym polem) ma niewiele sensu.

**Comment by pdodev** [comment]
1. Jeżeli już napisałeś ten kod, to dlaczego nie dałeś go do repozytorium (np. na branch-u WIP_gcfbn_clap_subcommands_question)  ? :-) Mając kod (najlepiej wykonywalny) jest łatwiej coś sprawdzić, poexperymentować itd.
2. Tak jak chcesz to zrobić jest (prawie) OK.
3. W tym konekście (clap/komendy CLI) warto nazywać struktury tak samo jak case-y enuma:
```rust
#[derive(Clap, Debug)]
enum SubCommand {
    #[clap(visible_alias = "gfg")]   // <--- możesz dodać coś takiego
    GraphFileGenerator(GraphFileGenerator) // zamiast: GraphFileGenerator(GraphFileGeneratorParameters),
    #[clap(visible_alias = "t")]   // <--- możesz dodać coś takiego
    Task(Task),   /// zamiast: Task(TaskData),
}
```
> Poza tym, wrapowanie PathBuf do TaskData (który jest structem z jednym polem) ma niewiele sensu.

To nie jest wrapowanie `PathBuf` do `TaskData` (semantycznie), tylko czytasz to jako (już po zmianie powyżej): 
task_file (typu `PathBuf`) jest wymaganym parametrem komendy `Task`.

4. Walidacja jednak nie musi zniknąć - walidator **może** być dodany do **pola** podkomendy:
```rust
/// ... dodaj tutaj opis komendy ... pojawi się na wyjściu przy --help
#[derive(Clap, Debug)]
#[clap(setting=AppSettings::ColoredHelp)]   // <---- to też może być w podkomendzie
struct Task {
    /// Task file with task data
    #[clap(long, short, parse(from_os_str), validator(file_exists))]
    pub task_file: PathBuf,
}
```
