### ISSUE TITLE
branch graph_file_generator: Implement acceptance tests (graphs/runner/tests)

### ISSUE THREAD

**Issue by pdodev** [gcfbn/learning_rust#53]
Patrz na testy: fails_because_edges_count_is_to_small i fails_because_edges_count_is_not_integer
One jeszcze nie działają (chodzi o ideę). 
Powinny zostać przeniesione do np. graphs/runner/tests/graph_file_generator_subcommand.rs.
Pozostałe testy z main.rs powinny okazać się niepotrzebne (ale z ich usuwaniem możesz poczekać, aż to co one robią będzie już zaimplementowane na poziomie testów akceptacyjnych)

**Comment by gcfbn** [comment]
merged to master in #71
