### ISSUE TITLE
generate_file_and_build_graph on gcfbn_benches

### ISSUE THREAD

**Issue by pdodev** [gcfbn/learning_rust#84]
Co myślisz o rozszerzeniu samego Makefile-a (o uruchamianie benchmark-ów), a w generate_file_and_build_graph make-a już byś nie wywoływał.
1) jeżeli pliku nie będzie ponieważ ktoś zapomni uruchomić make-a, to dostanie błąd (zapomniał - to jego problem)
2) uruchamiając benchmarki przez make-a będzie lepiej widać zależność danego benchmark-a od jego danych wejściowych. Np:

```make
bench_1000_nodes: generate_graph_1000_nodes
        cargo bench bench_1000_nodes
```

**Comment by gcfbn** [comment]
Okej, dodam to
